### ISSUE TITLE
Detected integration that restore_state.RestoreStateData.async_get_instance is deprecated

### ISSUE THREAD

**Issue by hardrockhodl** [custom-components/pyscript#487] opened 2023-07-12 13:05 UTC
```
2023-07-12 14:51:38.688 WARNING (MainThread) 
[homeassistant.helpers.frame] 
Detected integration that restore_state.RestoreStateData.async_get_instance is deprecated, 
and not intended to be called by custom components; 
Please refactor your code to use RestoreEntity instead; 
restore_state.async_get(hass) can be used in the meantime. 

Please report issue to the custom integration author for pyscript 
using this method at custom_components/pyscript/__init__.py,
line 83: restore_data = await RestoreStateData.async_get_instance(hass)
```

**Comment by craigbarratt** [comment] 2023-07-12 17:35
Duplicate of #473.

**Closed by craigbarratt** 2023-07-12 17:35 UTC
