### ISSUE TITLE
shutil.copy does not copy correct file size

### ISSUE THREAD

**Issue by GKHerping** [custom-components/pyscript#259] opened 2021-10-31 17:49 UTC
Setup: Synology with Docker running Home-Assistant with HACS integration and pyscript.

*Unsure if this is pyscript related, but assume it is a possibility*

I have made the following two functions:

```
@service

def getListOfFiles(dirName):
    import os
    # create a list of file and sub directories 
    # names in the given directory
    listOfFile = os.listdir(dirName)
    allFiles = list()
    # Iterate over all the entries
    for entry in listOfFile:
        # Create full path
        fullPath = os.path.join(dirName, entry)
        # If entry is a directory then get the list of files in this directory 
        if os.path.isdir(fullPath):
            allFiles = allFiles + getListOfFiles(fullPath)
        else:
            if fullPath.endswith('jpg'):
                allFiles.append(fullPath)
            elif fullPath.endswith('jpeg'):
                allFiles.append(fullPath)
            elif fullPath.endswith('png'):
                allFiles.append(fullPath)
    return allFiles

@service
def slideshow():
    import random
    import os
    import shutil
    path = '/Slideshow'
    listOfFiles = getListOfFiles(path)
    random_image = random.choice([x for x in listOfFiles])
    image_path = '{}'.format(random_image)
    shutil.copy2(image_path, '/config/www/slide.jpg')
```
Now everything works, BUT the destination file (slide.jpg) is never the correct size. It varies between 10kB - 1000kB, while the original image is often between 7-10 MB.

Any suggestions?

Running the same code (with different source and destination, of course) on macOS through Terminal works perfectly.

Same results using .copyfile and .copy

**Comment by dlashua** [comment] 2021-10-31 19:34
I tested shuti.copy2 with a 5MB file and the file is same size every time. 

My guess is that this is being run more than once at the same time. You can use `task.unique` to ensure that's not the case.

**Comment by GKHerping** [comment] 2021-10-31 19:35
As a novice in python, where and how do I insert task.unique?

**Comment by dlashua** [comment] 2021-10-31 19:37
It's a `pyscript` feature, actually. Right above `listOfFile = getList...` I would add `task.unique('slideshow')`.

**Comment by GKHerping** [comment] 2021-10-31 19:46
Unfortunately it did not help

**Comment by GKHerping** [comment] 2021-10-31 23:28
So digging around a lot I accidentally found out, that if the web interface for Synology (DSM) is open in the background, this situation happens. If I close the web interface, the image is copied over, in correct size. Any ideas on why, but more importantly, how to fix that?

**Comment by dlashua** [comment] 2021-11-02 14:21
I would recommend reducing your code bit by bit until you can find the smallest reproduceable test case. As it stands now I can't run your code because I don't have your files in place or whatever mechanism you're using to call the pyscript.slideshow service.

It might also help if we knew what was actually in slide.jpg. Is it a partial JPEG? Is it a full JPEG but not one of the expected files? Is it something else entirely?

**Comment by GKHerping** [comment] 2021-11-03 00:23
> It might also help if we knew what was actually in slide.jpg. Is it a partial JPEG? Is it a full JPEG but not one of the expected files? Is it something else entirely?

Firstly you'd have to change:
`path = '/Slideshow'` to a folder you have that contains subfolders and .jpg files (mine are all somewhere around 15-20 MB)
The /Slideshow is a volume mounted in docker specifically to /volume1/homes/Username/Photos/Moments

Secondly the `/config/www` folder is wherever you have the corresponding folder for home-assistant. 

In regards to the slide.jpg it shows as a jpg file, and the image is there, but the dimensions are (best case) shrunk from 6240x4160 to 1920x1080 and worst case from 4032x3024 to 120x90

For testing I've been using the Developer Tools - Services - pyscript.slideshow

**Comment by dlashua** [comment] 2021-11-03 02:58
It seems quite unlikely that `shutil.copy2` would be capable of changing the dimensions of an image. The JPEG file format can't just be truncated in order to make images smaller. Actual work has to be done that `shutil.copy2` just doesn't do. If the resulting `slide.jpg` is actually a jpeg that is viewable, then that file is coming from somewhere exactly as it is. I would examine the source directory more closely for hidden folders, thumbnails, and folders and files beginning with a ".". 

Another way to troubleshoot this would be to include exactly ONE image in the directory it's choosing files from, so you know exactly what the only possibility is, and see if it works as expected then.

Another technique would be to `log.info(listOfFiles)` and examine that output to see if there are any unexpected files in that list.

**Comment by dlashua** [comment] 2021-11-03 03:00
At any rate, this doesn't appear to be a bug/issue with Pyscript. You should close this issue and, perhaps, open a discussion instead seeking help with your project.

**Comment by craigbarratt** [comment] 2021-11-03 06:31
Agreed - closing this issue.

**Closed by craigbarratt** 2021-11-03 06:31 UTC

**Comment by GKHerping** [comment] 2021-11-03 13:26
Appreciate the help, I've found the issue, and as you suggested dlashua the issue was temporary files..
